name: epoch-core-test
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - pytest>=7.0.0
    - pytest-asyncio>=0.21.0
    - pytest-cov>=4.0.0
    - GitPython>=3.1.37
    - PyYAML>=6.0
