# EpochCore RAS Recursive Improvement Framework Configuration
# This is an example configuration file for the recursive improvement framework

autonomous:
  enabled: true
  interval_minutes: 60  # Run improvement cycles every hour
  max_concurrent_improvements: 3

logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  file: recursive_improvement.log

subsystems:
  agents:
    enabled: true
    priority: 1  # Higher priority = more important
  dags:
    enabled: true
    priority: 2
  capsules:
    enabled: true
    priority: 3
  ethics:
    enabled: true
    priority: 1  # Ethics should be high priority
  ml:
    enabled: true
    priority: 2

# Strategy-specific configurations
strategies:
  performance_optimization:
    improvement_threshold: 0.1  # Minimum 10% improvement needed
    max_iterations: 5
  
  resource_optimization:
    memory_threshold_mb: 1000
    cpu_threshold_percent: 80
    
  reliability_enhancement:
    min_success_rate: 0.95
    error_rate_threshold: 0.01

# Metrics and monitoring
metrics:
  retention_days: 30
  export_interval_hours: 24
  alert_on_failures: true
  
# Performance settings
performance:
  analysis_timeout_seconds: 30
  improvement_timeout_seconds: 120
  max_memory_usage_mb: 2000