deployment:
  deployment_key: recursive_autonomy_deployment
  target_repos: []
  validation_required: true
framework:
  cross_repo_enabled: true
  improvement_threshold: 0.8
  max_recursion_depth: 10
  monitoring_enabled: true
innovations:
  api_discovery:
    discovery_interval: 3600
    enabled: true
  autonomous_simulation:
    enabled: true
    max_scenarios: 10
  hierarchical_governance:
    enabled: true
    max_levels: 5
  ip_generation:
    enabled: true
    legal_compliance: true
  meta_recursive_auditing:
    enabled: true
    max_depth: 5
  recursive_agent_networks:
    enabled: true
    max_agents: 50
  recursive_data_pipeline:
    enabled: true
    max_nodes: 20
  recursive_knowledge_graph:
    enabled: true
    max_nodes: 100
  security_testing:
    enabled: true
    scan_interval: 1800
  talent_network:
    enabled: true
    skill_tracking: true
