name: Bug Report
description: File a bug report
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Version
      description: What version are you running?
    validations:
      required: true
      
  - type: dropdown
    id: environment
    attributes:
      label: What environment are you seeing the problem on?
      options:
        - Development
        - Staging
        - Production
    validations:
      required: true
