# Continuity Ritual Configuration
# EpochCore RAS Maintenance Automation

rituals:
  daily:
    enabled: true
    schedule: "0 2 * * *"  # 2:00 AM daily
    tasks:
      - system_health_check
      - log_rotation
      - temp_cleanup
      - metrics_collection
      
  weekly:
    enabled: true
    schedule: "0 3 * * 1"  # 3:00 AM Monday
    tasks:
      - full_backup
      - dependency_update_check
      - performance_analysis
      - security_scan
      
  monthly:
    enabled: true
    schedule: "0 4 1 * *"  # 4:00 AM 1st of month
    tasks:
      - archive_old_logs
      - cleanup_old_backups
      - system_optimization
      - comprehensive_audit

monitoring:
  resource_thresholds:
    cpu_percent: 80
    memory_percent: 85
    disk_percent: 90
    
notifications:
  enabled: true
  channels:
    - log
    - file
