# Merge Automation Configuration
# EpochCore RAS Automated Merge System

merge_strategies:
  auto_merge:
    enabled: true
    conditions:
      - all_checks_passed
      - no_conflicts
      - approved_by_maintainer
      
  conflict_resolution:
    strategy: "auto"  # auto, manual, skip
    prefer: "incoming"  # incoming, current, manual
    
quality_gates:
  pre_merge:
    - lint_check
    - test_suite
    - security_scan
    - integration_test
    
  post_merge:
    - deployment_test
    - smoke_test
    - rollback_validation
    
notifications:
  success: true
  failure: true
  conflict: true
  
rollback:
  enabled: true
  triggers:
    - test_failure
    - deployment_failure
    - critical_error
    
  strategy: "backup_restore"  # backup_restore, git_revert
