# Workflow Conflict Resolver Configuration
# EpochCore RAS Enhanced PR Management System

merge_queue:
  max_concurrent_merges: 3
  priority_weights:
    hotfix: 10
    security: 9
    critical: 8
    bugfix: 7
    enhancement: 6
    feature: 5
    refactor: 4
    documentation: 3
    chore: 2
  merge_window:
    start_hour: 9   # 9 AM UTC
    end_hour: 17    # 5 PM UTC
    timezone: "UTC"
    blocked_days: ["saturday", "sunday"]
    blocked_dates: []  # Specific dates to block merges
  batch_processing:
    enabled: true
    batch_size: 5
    delay_between_batches: 300  # 5 minutes

conflict_resolution:
  auto_resolution_strategies:
    documentation: "prefer_incoming"     # Docs: take the new changes
    configuration: "merge_both"          # Config: try to merge both
    code: "require_manual"               # Code: always require manual review
    tests: "prefer_latest"               # Tests: prefer the newer version
    dependencies: "prefer_incoming"      # Dependencies: take updates
  conflict_severity_thresholds:
    low: 5       # files
    medium: 15   # files  
    high: 30     # files
    critical: 50 # files
  auto_resolve_timeout: 600      # 10 minutes
  manual_review_timeout: 3600    # 1 hour
  max_auto_resolve_attempts: 3
  conflict_patterns:
    always_manual:
      - "*.py"
      - "*.js"
      - "*.ts"
      - "*.java"
      - "*.go"
      - "*.rs"
      - "*.cpp"
      - "*.h"
    safe_auto_resolve:
      - "*.md"
      - "*.txt"
      - "*.yml"
      - "*.yaml"
      - "*.json"
      - "README*"
      - "CHANGELOG*"
      - "docs/*"

quality_gates:
  required_checks:
    - "lint"
    - "test_unit"
    - "test_integration" 
    - "security_scan"
    - "build"
  optional_checks:
    - "performance_test"
    - "accessibility_test"
    - "documentation_check"
    - "dependency_check"
  failure_handling:
    required_failure: "block_merge"
    optional_failure: "warn_but_continue"
  timeout_minutes: 30
  retry_attempts: 2

notifications:
  merge_success: true
  merge_failure: true
  conflict_detected: true
  queue_status: true
  manual_review_required: true
  batch_complete: true
  channels:
    - type: "log"
      level: "info"
    - type: "github_comment"
      enabled: true
    # Future: Slack, email, etc.

cross_repo_sync:
  enabled: true
  sync_branches: ["main", "develop", "staging"]
  propagation_delay: 300        # 5 minutes between repos
  max_repos: 20
  sync_patterns:
    - "recursive_improvement/**"
    - "integration.py"
    - "config/**"
    - ".github/workflows/**"
  exclude_patterns:
    - "logs/**"
    - "*.log"
    - "__pycache__/**"
    - "node_modules/**"

repository_monitoring:
  repositories:
    - "Jvryan92/epochcore_RAS"
    - "Jvryan92/EpochCore_OS"
    - "EpochCore5/epoch5-template"
    - "Jvryan92/epoch-agentic-bundle"
    - "Jvryan92/epoch-mesh"
    - "Jvryan92/StategyDECK"
    - "Jvryan92/SaaS-01"
    - "Jvryan92/SaaS-02"
    - "Jvryan92/SaaS-03"
    - "Jvryan92/SaaS-04"
    - "Jvryan92/SaaS-05"
    - "Jvryan92/SaaS-08"
    - "Jvryan92/SaaS-09"
  refresh_interval: 900         # 15 minutes
  max_pr_age_days: 30          # Alert if PR older than 30 days

automation_rules:
  auto_merge_conditions:
    - "approved_by_maintainer"
    - "all_checks_passed"
    - "no_conflicts"
    - "not_draft"
    - "target_branch_protected"
  dependency_resolution:
    enabled: true
    max_depth: 5                # Max dependency chain length
    circular_dependency_handling: "error"
  rollback_triggers:
    - "test_failure_post_merge"
    - "deployment_failure"
    - "critical_error"
    - "manual_request"

performance:
  cache_ttl: 3600              # 1 hour
  max_concurrent_api_calls: 10
  api_call_timeout: 30         # seconds
  github_api_rate_limit_buffer: 100  # Keep this many calls in reserve

logging:
  level: "INFO"
  file: "logs/workflow_resolver.log"
  max_size_mb: 100
  backup_count: 5
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  
metrics:
  enabled: true
  collection_interval: 300     # 5 minutes
  retention_days: 30
  metrics_file: "logs/workflow_metrics.json"
  track:
    - "merge_success_rate"
    - "average_merge_time"
    - "conflict_resolution_rate"
    - "queue_size"
    - "api_usage"