name: Continuous Deployment

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Generate icons
      run: |
        python scripts/generate_icons.py
        echo "Generated icon variants:"
        find assets/icons -name "*.svg" | wc -l
        find assets/icons -name "*.png" | wc -l

    - name: Configure git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Commit generated assets
      run: |
        git add assets/icons/
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "🤖 Auto-generate icon assets [skip ci]"
          git push
        fi

    - name: Create release with assets
      if: success()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # Create a timestamped release
        TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
        TAG_NAME="assets-$TIMESTAMP"
        
        # Create and push tag
        git tag $TAG_NAME
        git push origin $TAG_NAME
        
        # Create archive of generated assets
        tar -czf strategy-deck-assets.tar.gz assets/icons/
        
        # Create release
        gh release create $TAG_NAME \
          --title "StrategyDECK Assets $TIMESTAMP" \
          --notes "Auto-generated icon assets from commit ${GITHUB_SHA:0:7}" \
          strategy-deck-assets.tar.gz

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: success()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./assets/icons
        destination_dir: icons
        commit_message: "🚀 Deploy icon assets to GitHub Pages"