name: StrategyDECK CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 scripts/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. GitHub editor is 127 chars wide
        flake8 scripts/ --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Format check with black
      run: |
        black --check scripts/ tests/

    - name: Test icon generation script
      run: |
        python scripts/generate_icons.py
        # Verify that SVG files were generated
        test -d assets/icons/light
        test -d assets/icons/dark
        find assets/icons -name "*.svg" | wc -l | grep -q "10"

    - name: Run tests with pytest
      run: |
        pytest tests/ -v

    - name: Upload generated icons as artifacts
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: generated-icons-python-${{ matrix.python-version }}
        path: assets/icons/
        retention-days: 7
=======
        
    - name: Run type checks
      run: |
        mypy .
        
    - name: Run security scan
      run: |
        safety check
        bandit -r .
        
    - name: Run tests
      run: |
        pytest --cov=. --cov-report=xml
        
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true

  build:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
        
    - name: Build package
      run: |
        pip install build
        python -m build
        
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: dist
        path: dist/
>>>>>>> epoch5/main
