name: Ops – Generate Content Drafts
on:
  workflow_dispatch:
jobs:
  content:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: 18, cache: 'npm' }
      - run: npm ci
      - run: npm run ops:content
      - name: Commit drafts
        run: |
          git config user.name "epochroot-bot"
          git config user.email "bot@users.noreply.github.com"
          git add ops/content/drafts || true
          git commit -m "chore(content): generate drafts" || echo "No changes"
          git push